config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
	scope constraints: { subdomain: '' } do
		root 'tnf_landing_page#index'
	end

	scope '/auth', constraints: { subdomain: 'work' } do
		devise_for :users
	end

	scope constraints: { subdomain: 'work' }, as: :work do

		root 'static_pages#dashboard'

		resource :user, only: [] do
			post :pay_out
		end
		resource :user_profile, only: [:edit, :update]
		resources(:user_vk_contacts_files, only: [:index, :show, :update, :edit]) { member { get :download } }
		resources(:user_vk_contacts_records, only: [:index, :update, :edit, :destroy]) { member { get :download } }

		get 'vkontakte_contacts_collector', to: 'static_pages#vkontakte_contacts_collector'
		get 'pricing_plans', to: 'static_pages#pricing_plans'
		get 'pmvf', to: 'static_pages#pmvf'
		get 'referrals', to: 'static_pages#referrals'
		get 'faq', to: 'static_pages#faq'

		scope 'vkontakte_oauth', as: :vk_o_auth do
			get 'authorize', to: 'vk_o_auth#authorize'
			get 'logout', to: 'vk_o_auth#logout'
		end

		scope 'vkontakte_contacts', as: :vkontakte_contacts do
			post 'upload', to: 'vk_contacts_load#upload_contacts'
		end

		namespace :admin do
			root 'static_pages#dashboard'
			resources :users, only: [:index, :edit, :show, :update]
			resources :perfect_money_merchant_accounts
			resources :perfect_money_merchant_payments
		end

		authenticate :user do
			mount Sidekiq::Web => '/admin/sidekiq'
		end
	end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::ApplicationController
	def dashboard
		@pending_pay_out = (User.sum(:referral_earned) - User.sum(:referral_paid_out)).round(2)
		@total_usd_amount = PerfectMoneyMerchant::Account::Unit.where(currency: :usd).sum(:balance)
		@total_users_count = User.count
		@total_user_vk_contacts_records_count = UserVkContactsRecord.count
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def dashboard
	end

	def vkontakte_contacts_collector
		vk_oauth_host = 'https://oauth.vk.com/authorize'
		vk_oauth_params = {
			client_id: 4523313,
			scope: [
				:friends,
				:groups,
				:offline
			].join(','),
			redirect_uri: work_vk_o_auth_authorize_url,
			v: '5.24',
			response_type: :code
		}.map { |k, v| "#{k}=#{v}" }.join('&')
		@vk_oauth_url = "#{vk_oauth_host}?#{vk_oauth_params}"
		@user_vk_contacts_records = current_user.user_vk_contacts_records.order('created_at DESC').last(10)
	end

	def pricing_plans
		@pricing_plan_sci = UserVkContactsCollectorPermission::PACKAGES.inject({}) do |m, e|
			if current_user.vcc_permission.package.blank? or e[:level] > UserVkContactsCollectorPermission.get_package_by(:name, @current_user.vcc_permission.package.to_sym)[:level]
				m[e[:name]] = generate_pricing_plan_pm_sci(e[:name].to_s, e[:price])
			end; m
		end
	end

	def pmvf

	end

	def referrals

	end

	def faq

	end

	private

	def generate_pricing_plan_pm_sci(name, price)
		PerfectMoneyMerchant::SCI.new(
			price: price,
			payee: PerfectMoneyMerchant::Account.obtain_deposit_account(:usd),
			additional: {
				user_id: current_user.id,
				pricing_plan_name: name,
				pricing_plan_price: price
			},
			verification: [:user_id, :pricing_plan_name, :pricing_plan_price],
			purpose: 'pricing_plan',
			redirect_url: work_pricing_plans_url
		)
	end
end

app/views/static_pages/dashboard.html.erb
<%= alert_box context: :warning do %>
    <p>
      <b>Внимание:</b> перед тем как оплачивать услуги TNF и пользоваться ими,
      сначала <%= link_to 'прочтите FAQ', work_faq_url %>.
    </p>
<%- end -%>

<!--<div class="row m-b">-->
  <!--<div class="col-md-4 col-sm-6"><%= link_to fa_icon('vk', text: t('translations.vk_contacts_collector')), work_vkontakte_contacts_collector_url, class: 'btn btn-white btn-block' -%></div>-->
  <!--<div class="col-md-4 col-sm-6"><%= link_to fa_icon('diamond', text: t('translations.pricing_n_plans')), work_pricing_plans_url, class: 'btn btn-white btn-block' -%></div>-->
  <!--<div class="col-md-4 col-sm-6"><%= link_to fa_icon('dollar', text: t('translations.referrals')), work_referrals_url, class: 'btn btn-white btn-block' -%></div>-->
<!--</div>-->

<div class="row">
  <div class="col-lg-12">
    <%= render 'static_pages/dashboard/tnf_intro' -%>
  </div>
</div>
<!--<div class="row">-->
<!--<div class="col-lg-12 text-center">-->
<!--<iframe src="https://www.google.com/calendar/embed?src=iupu1br2q89aka9vqj499iibbs%40group.calendar.google.com" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>-->
<!--</div>-->
<!--</div>-->

app/views/static_pages/faq.html.erb
<div class="panel-group" id="pmvf-faq-accordion">
  <div class="panel">
    <div class="panel-heading active-panel">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse1">
          Как правильно использовать программу "Сборщик контактов Вконтакте"
        </a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
        <p>Первым делом стоит отметить, что вы не можете каждый день скачивать десятки тысяч контактов. Вы не спамом
          занимаетесь и не собираете себе базу контактов. Вы предлагаете свой бизнес другим людям.</p>

        <p><b>В независимости от купленного тарифного пакета вы будете иметь ограниченное количество запросов на сбор
          контактов в день.</b></p>

        <p>Видеоурок скоро будет</p>

        <p>
          <small class="text-muted">С ув. администрация TNF.</small>
        </p>

      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading active-panel">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse2">
          Платежные системы и выплаты.
        </a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
        <p>TNF работает с платежной системой PerfectMoney.</p>

        <p>Выплаты - инстант</p>

        <p>
          <small class="text-muted">С ув. администрация TNF.</small>
        </p>
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading active-panel">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse3">
          Как работает партнерская программа?
        </a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
      <div class="panel-body">
        <p>Партнерская программа активна сразу после регистрации</p>

        <p>Изначально вы получаете реферальные в <b>15% с первой линии и 0% со второй</b></p>

        <p>Чтобы получить реферальные в <b>30% с первой линии и 20% со второй</b> вам необходимо:</p>
        <ul>
          <li>оплатить пакет <b class="text-navy">Skilled120 или выше</b>;</li>
          <li><b>10 ваших лично-приглашенных человек</b>, должны оплатить пакет
            <b class="text-navy">Skilled120 или выше</b></li>
        </ul>

        <p>Чтобы получить реферальные в <b>45% с первой линии и 30% со второй</b> вам необходимо:</p>
        <ul>
          <li>оплатить пакет <b class="text-navy">Seasoned240 или выше</b>;</li>
          <li><b>5 ваших лично-приглашенных человек</b>, должны оплатить пакет
            <b class="text-navy">Seasoned240 или выше</b></li>
        </ul>

        <p>
          <small class="text-muted">С ув. администрация TNF.</small>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/pmvf.html.erb
<%= ah_ibox do -%>
    <%= ah_ibox_heading do -%>
        <%= render partial: 'static_pages/pmvf/heading' -%>
        <%- unless @current_user.inviter.nil? -%>
            <%= render partial: 'static_pages/pmvf/social_networks', locals: { user: @current_user.inviter } -%>
        <%- end -%>
        <%= render partial: 'static_pages/pmvf/videos' -%>
    <%- end -%>
    <%= ah_ibox_content do -%>
        <%= nav do %>
            <%= link_to fa_icon('table', text: t('translations.description')), '#pmvf-description', data: { toggle: 'tab' } -%>
            <%= link_to fa_icon('star', text: t('translations.features')), '#pmvf-features', data: { toggle: 'tab' } -%>
            <%= link_to fa_icon('question', text: 'FAQ'), '#pmvf-faq', data: { toggle: 'tab' } -%>
            <%= link_to fa_icon('coffee', text: t('translations.schedule')), '#pmvf-schedule', data: { toggle: 'tab' } -%>
        <% end %>

        <div class="panel-body">
          <div class="tab-content">
            <div class="tab-pane fade active in" id="pmvf-description">
              <%= render partial: 'static_pages/pmvf/description' -%>
            </div>
            <div class="tab-pane fade" id="pmvf-features">
              <%= render partial: 'static_pages/pmvf/features' -%>
            </div>
            <div class="tab-pane fade" id="pmvf-faq">
              <%= render partial: 'static_pages/pmvf/faq' -%>
            </div>
            <div class="tab-pane fade" id="pmvf-schedule">
              <div class="text-center">
                <iframe src="https://www.google.com/calendar/embed?src=iupu1br2q89aka9vqj499iibbs%40group.calendar.google.com" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
              </div>
            </div>
            <div class="tab-pane fade" id="pmvf"></div>
          </div>
        </div>
        <small class="m-t text-muted">Вы можете помочь TNF дополнить информацию о Меркурие отослав свое предложение по
          адресу
          <a href="mailto:thenewfriendsnet@gmail.com">thenewfriendsnet@gmail.com</a></small>
    <%- end -%>
<%- end -%>

app/views/static_pages/pricing_plans.html.erb
<%- if PerfectMoneyMerchant::Account.count > 0 -%>
    <%- unless @current_user.vcc_permission.package.blank? -%>
        <div class="row">
          <div class="col-md-6">
            <%= ah_ibox do -%>
                <%= ah_ibox_content do -%>
                    <h2>Мои оплаченные пакеты</h2>

                    <h3>Сборщик контактов Вконтакте</h3>
                    <table class="table table-striped">
                      <thead>
                      <tr>
                        <th>Название пакета</th>
                        <th>Осталось до конца</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td><%= fa_icon('vk',text: @current_user.vcc_permission.package.to_s.camelcase) %></td>
                        <td><%= fa_icon('clock-o',text: @current_user.vcc_permission.decorate.expires_in_words) %></td>
                      </tr>
                      </tbody>
                    </table>
                <%- end -%>
            <%- end -%>
          </div>
        </div>
    <%- end -%>
    <%- if @pricing_plan_sci.size.zero? -%>
        <h2>У вас сейчас оплачен максимальный пакет</h2>
    <%- end -%>
    <div class="row">
      <%- @pricing_plan_sci.each do |name, sci| -%>
          <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="pricing-widget white-bg colorful-widget">
              <div class="pricing-icon">
                <div class="pricing-icon-inner">
                  <i class="fa fa-vk"></i>
                </div>
              </div>

              <div class="text-center">
                <h4>Сборщик контактов Вконтакте</h4>

                <h2 class="text-navy"><%= name.to_s.camelcase %></h2>

                <h2 class="pricing-value">
                  <%= "$#{sci.payment_amount}" %>/
                  <small><%= "#{UserVkContactsCollectorPermission.get_package_by(:name, name)[:duration_in_days]} дней" %></small>
                </h2>
              </div>

              <ul class="pricing-service">
                <%- t("translations.pricing_plan.#{name}").each_line do |_feature| -%>
                    <li><%= raw(_feature) -%></li>
                <%- end -%>
              </ul>

              <div class="m-top-md text-center">
                <%= render partial: 'static_pages/pricing_plans/perfect_money_form', locals: { sci: sci } %>
              </div>
            </div>
            <!-- ./pricing-widget -->
          </div>
      <%- end -%>
      <!-- .col -->
    </div>
<%- else -%>
    <div class="text-center">
      <h2>Технические проблемы.</h2>

      <h3>Мы уже отправили нашего лучшего специалиста решить их.</h3>
    </div>
<%- end -%>

app/views/static_pages/referrals.html.erb
<% if @current_user.decorate.profile_fields_filled? %>
    <%- unless @current_user.inviter.nil? -%>
        <%= ah_ibox do -%>
            <%= ah_ibox_content do -%>
                <h2>Пригласитель</h2>

                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th><%= UserProfile.human_attribute_name(:first_name) %></th>
                    <th><%= UserProfile.human_attribute_name(:last_name) %></th>
                    <th><%= UserProfile.human_attribute_name(:country) %></th>
                    <th><%= UserProfile.human_attribute_name(:city) %></th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td><%= @current_user.inviter.user_profile.first_name %></td>
                    <td><%= @current_user.inviter.user_profile.last_name %></td>
                    <td><%= @current_user.inviter.user_profile.country %></td>
                    <td><%= @current_user.inviter.user_profile.city %></td>
                  </tr>
                  </tbody>
                </table>

                <%= render partial: 'shared/user_social_networks', locals: { user: @current_user.inviter } %>

            <%- end -%>
        <%- end -%>
    <%- end -%>
    <%= ah_ibox do -%>
        <%= ah_ibox_content do -%>
            <h2>Статистика</h2>
            <table class="table table-white table-striped">
              <tbody>
              <tr>
                <td>Реферальные c 1й линии</td>
                <td><%= "#{@current_user.referral_award_level_1}%" %></td>
              </tr>
              <tr>
                <td>Реферальные с 2й линии</td>
                <td><%= "#{@current_user.referral_award_level_2}%" %></td>
              </tr>
              <tr>
                <td>Заработано</td>
                <td><%= fa_icon('dollar', text: @current_user.referral_earned) %></td>
              </tr>
              <tr>
                <td>Выплачено</td>
                <td><%= fa_icon('dollar', text: @current_user.referral_paid_out) %></td>
              </tr>
              <%- if @current_user.decorate.referral_balance > 0 -%>
                  <tr>
                    <td>
                      <%= link_to fa_icon('level-up', text: "Выплатить на #{@current_user.user_profile.pm_usd_acct}"), pay_out_work_user_url,
		                      method: :post,
		                      class: 'text-danger',
		                      data: { confirm: "Вы точно хотите выплатить $#{@current_user.decorate.referral_balance} на #{@current_user.user_profile.pm_usd_acct}?" }
                      %>
                    </td>
                    <td class="text-danger"><%= fa_icon('dollar', text: @current_user.decorate.referral_balance) %></td>
                  </tr>
              <%- end -%>
              <tr>
                <td>Реферралов с Skilled120 или выше</td>
                <td><%= current_user.get_referrals_by(vk_contacts_collector: { package_name: :skilled_120_or_greater }).count %></td>
              </tr>
              <tr>
                <td>Реферралов с Seasoned240 или выше</td>
                <td><%= current_user.get_referrals_by(vk_contacts_collector: { package_name: :seasoned_240_or_greater }).count %></td>
              </tr>
              </tbody>
            </table>

            <%- if @current_user.referral_award == 0 -%>
            <%- end -%>

            <div class="m-b">
              <p>

              </p>
            </div>

            <div class="m-b text-muted" style="font-size: 0.85em;">
              <p>Чтобы получить реферальные в <b>30% с первой линии и 20% со второй</b> вам необходимо:</p>
              <ul>
                <li>оплатить пакет <b class="text-navy">Skilled120 или выше</b>;</li>
                <li><b>10 ваших лично-приглашенных человек</b>, должны оплатить пакет
                  <b class="text-navy">Skilled120 или выше</b></li>
              </ul>

              <p>Чтобы получить реферальные в <b>45% с первой линии и 30% со второй</b> вам необходимо:</p>
              <ul>
                <li>оплатить пакет <b class="text-navy">Seasoned240 или выше</b>;</li>
                <li><b>5 ваших лично-приглашенных человек</b>, должны оплатить пакет
                  <b class="text-navy">Seasoned240 или выше</b></li>
              </ul>

              <p></p>

              <p><b>Выплаты инстант.</b></p>

              <p>
                Убедитесь, что вы верно указали кошелек Perfect Money
                в <%= link_to 'настройках профиля', edit_work_user_profile_url %>
              </p>

              <p><b>Реф. ссылка: <%= root_url(ref: @current_user.user_profile.username) %></b></p>

              <p><%= render 'shared/talk_to_admin', text: 'Пообщаться с администрацией' %></p>
            </div>


        <%- end -%>
    <%- end -%>
    <%= ah_ibox do -%>
        <%= ah_ibox_content do -%>
            <h2>
              Рефералы
              <small class="text-muted">1 уровня</small>
            </h2>
            <%= render 'static_pages/referrals/table', referrals: @current_user.referrals.order('created_at DESC') %>
        <%- end -%>
    <%- end -%>

    <%= ah_ibox do -%>
        <%= ah_ibox_content do -%>
            <h2>Платежи</h2>
            <%= render 'static_pages/referrals/r_payments_table', referral_payments: @current_user.user_referral_payments.order('created_at DESC') %>
        <%- end -%>
    <%- end -%>
<%- else -%>
    <div class="text-center">
      <h2>Вы не можете видеть своих реферралов, пока не заполните свой профиль</h2>

      <h3><%= t('translations.go_to') -%> <%= link_to t('translations.profile'), edit_work_user_profile_url %></h3>
    </div>
<%- end -%>

app/views/static_pages/vkontakte_contacts_collector.html.erb
<% if @current_user.decorate.profile_fields_filled? %>
    <div class="row">
      <div class="col-lg-12">
        <%- if @current_user_d.pricing_plan_purchased?(:vk_contacts_collector) -%>
            <%- if can? :create, UserVkContactsRecord -%>
                <%= render 'static_pages/vkontakte_contacts_collector/vk_contacts_collector' %>
            <%- else -%>
                <% if @current_user.vcc_permission.can_create? %>
                    <%- if @current_user_d.vk_contacts_request_left.zero? -%>
                        <%= render 'static_pages/vkontakte_contacts_collector/out_of_limit' %>
                        <hr/>
                    <%- end -%>
                <%- else -%>
                    <div class="text-center">
                      <div>
                        <%= fa_icon('exclamation-triangle 4x') -%>
                      </div>
                      <h2><%= raw(t('translations.user_vk_contacts_file.no_permission.create')) -%></h2>
                    </div>
                    <hr/>
                <%- end -%>
            <%- end -%>
            <%- if can? :read, UserVkContactsRecord -%>
            <%- else -%>
                <div class="text-center">
                  <div>
                    <%= fa_icon('exclamation-triangle 4x') -%>
                  </div>
                  <h2><%= raw(t('translations.user_vk_contacts_file.no_permission.read')) -%></h2>
                </div>
            <%- end -%>
        <%- else -%>
            <div class="text-center">
              <div>
                <%= fa_icon('exclamation-triangle 4x') -%>
              </div>
              <h2><%= t('translations.user_vk_contacts_file.no_permission.not_paid') -%></h2>

              <h3>
                <%= t('translations.go_to') -%>
                <%= link_to t('translations.pricing_n_plans'), work_pricing_plans_url %>
              </h3>
            </div>
        <%- end -%>
      </div>
    </div>
<%- else -%>
    <div class="text-center">
      <div>
        <%= fa_icon('exclamation-triangle 4x') -%>
      </div>

      <h2>Вы не можете использовать ВК сборщик контактов. <br/> Заполните свой профиль</h2>

      <h3><%= t('translations.go_to') -%> <%= link_to t('translations.profile'), edit_work_user_profile_url %></h3>
    </div>
<%- end -%>