config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
	scope constraints: { subdomain: '' } do
		root 'tnf_landing_page#index'
	end

	scope '/auth', constraints: { subdomain: 'work' } do
		devise_for :users
	end

	scope constraints: { subdomain: 'work' }, as: :work do

		root 'static_pages#dashboard'

		resource :user, only: [] do
			post :pay_out
		end
		resource :user_profile, only: [:edit, :update]
		resources(:user_vk_contacts_files, only: [:index, :show, :update, :edit]) { member { get :download } }
		resources(:user_vk_contacts_records, only: [:index, :update, :edit, :destroy]) { member { get :download } }

		get 'vkontakte_contacts_collector', to: 'static_pages#vkontakte_contacts_collector'
		get 'pricing_plans', to: 'static_pages#pricing_plans'
		get 'pmvf', to: 'static_pages#pmvf'
		get 'referrals', to: 'static_pages#referrals'
		get 'faq', to: 'static_pages#faq'

		scope 'vkontakte_oauth', as: :vk_o_auth do
			get 'authorize', to: 'vk_o_auth#authorize'
			get 'logout', to: 'vk_o_auth#logout'
		end

		scope 'vkontakte_contacts', as: :vkontakte_contacts do
			post 'upload', to: 'vk_contacts_load#upload_contacts'
		end

		namespace :admin do
			root 'static_pages#dashboard'
			resources :users, only: [:index, :edit, :show, :update]
			resources :perfect_money_merchant_accounts
			resources :perfect_money_merchant_payments
		end

		authenticate :user do
			mount Sidekiq::Web => '/admin/sidekiq'
		end
	end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::ApplicationController
	def dashboard
		@pending_pay_out = (User.sum(:referral_earned) - User.sum(:referral_paid_out)).round(2)
		@total_usd_amount = PerfectMoneyMerchant::Account::Unit.where(currency: :usd).sum(:balance)
		@total_users_count = User.count
		@total_user_vk_contacts_records_count = UserVkContactsRecord.count
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def dashboard
	end

	def vkontakte_contacts_collector
		vk_oauth_host = 'https://oauth.vk.com/authorize'
		vk_oauth_params = {
			client_id: 4523313,
			scope: [
				:friends,
				:groups,
				:offline
			].join(','),
			redirect_uri: work_vk_o_auth_authorize_url,
			v: '5.24',
			response_type: :code
		}.map { |k, v| "#{k}=#{v}" }.join('&')
		@vk_oauth_url = "#{vk_oauth_host}?#{vk_oauth_params}"
		@user_vk_contacts_records = current_user.user_vk_contacts_records.order('created_at DESC').last(10)
	end

	def pricing_plans
		@pricing_plan_sci = UserVkContactsCollectorPermission::PACKAGES.inject({}) do |m, e|
			if current_user.vcc_permission.package.blank? or e[:level] > UserVkContactsCollectorPermission.get_package_by(:name, @current_user.vcc_permission.package.to_sym)[:level]
				m[e[:name]] = generate_pricing_plan_pm_sci(e[:name].to_s, e[:price])
			end; m
		end
	end

	def pmvf

	end

	def referrals

	end

	def faq

	end

	private

	def generate_pricing_plan_pm_sci(name, price)
		PerfectMoneyMerchant::SCI.new(
			price: price,
			payee: PerfectMoneyMerchant::Account.obtain_deposit_account(:usd),
			additional: {
				user_id: current_user.id,
				pricing_plan_name: name,
				pricing_plan_price: price
			},
			verification: [:user_id, :pricing_plan_name, :pricing_plan_price],
			purpose: 'pricing_plan',
			redirect_url: work_pricing_plans_url
		)
	end
end

app/views/static_pages/dashboard/_pmvf_intro.html.erb
<%= ah_ibox do -%>
    <%= ah_ibox_heading do -%>
        <%= render partial: 'static_pages/pmvf/heading' -%>
        <div class="m-t">
          <%= link_to t('translations.learn_more'), work_pmvf_path, class: 'btn btn-primary' -%>
        </div>
    <%- end -%>
    <%= ah_ibox_content do -%>
        <%= render partial: 'static_pages/pmvf/features' -%>
    <%- end -%>
<%- end -%>

app/views/static_pages/dashboard/_tnf_intro.html.erb
<%= ah_ibox do -%>
    <%= ah_ibox_heading do -%>
        <div>
          <h3> The New Friends </h3>

          <h4>Ваш незаменимый помощник</h4>

          <p>
            Программа “The New Friends" без больших денежных затрат поможет Вам создать постоянный поток новых
            Партнеров, Клиентов и Потребителей в ваш собственный бизнес.
          </p>

          <p>
            Программа “The New Friends" станет для Вас незаменимым помощником для установления новых связей в
            социальных сетях, таких как Вонтакте, Facebook, Twitter и т.д.. Ведь друзья в социальных сетях, а их может
            быть очень много, являются вашими потенциальными партнерами.
          </p>
        </div>
        <div>
          <h3>Планы</h3>
          <ul>
            <li>Внутренний сервис <b>массовой рассылки сообщений ВК</b> с автозаполнение всплывающее капчи.</li>
            <li>Внутренний сервис <b>автоматического обмена лайками ВК</b>.</li>
            <li>Внутренний сервис <b>массового фолловинга ВК</b>.</li>
          </ul>
        </div>
        <div>
          <h3>Новости
            <small>
              <a href="https://vk.com/thenewfriendsnet" target="_blank" class="btn btn-primary btn-outline"><%= fa_icon('external-link') %></a>
            </small>
          </h3>

        </div>
        <div>
          <h3>
            Мы в сети:
            <%= link_to fa_icon('vk'), 'https://vk.com/thenewfriendsnet', class: 'btn btn-primary btn-outline', target: '_blank' -%>
          </h3>
        </div>
        <div>
          <h3>Как работает программа "New Friends"?</h3>

          <h4>
            <a href="https://www.youtube.com/watch?v=OZiBSpfHC_g" target="_blank"><%= fa_icon('external-link') %>
              Открыть видеоролик-демонстрацию
            </a>
          </h4>

          <p>Программа дает Вам возможность автоматически собирать в социальных сетях следующие данные:</p>

          <ul>
            <li>Вконтакте
              <small class="text-muted">(Facebook в разработке)</small>
              <ul>
                <li>ФИО</li>
                <li>Skype</li>
                <li>Телефон</li>
                <li>Instagram аккаунт</li>
                <li>Twitter аккаунт</li>
              </ul>
            </li>
          </ul>

          <p>С полученной информацией программа дает возможность совершать следующие действия:</p>

          <ul class="list">
            <li class="text-muted">
              Вконтакте, Facebook
              <small class="text-muted">(в разработке)</small>
              <ul>
                <li>Отправлять запрос на добавление в друзья</li>
                <li>Рассылка сообщений</li>
              </ul>
            </li>
            <li>
              Skype
              <ul>
                <li>Импорт контактов из <b>VCF</b> файла</li>
                <li>Рассылка сообщений
                  <small class="text-muted">(Clownfish: отдельная десктопная прогамма под Windows\Linux\Mac)</small>
                </li>
              </ul>
            </li>
          </ul>

          <p>
            Как Вы видите, Программа “The New Friends" является мощным ресурсом для работы в социальных сетях. Вы
            получите возможность быстро и эффективно привлекать новых партнеров в Ваш бизнес, которая станет Вашим
            незаменимым Помощником!
          </p>
        </div>
        <div>
          <h3>Реферальная система</h3>

          <p>TNF работает с платежной системой PerfectMoney. Выплаты реферальных производятся инстантом.</p>

          <p>У сборщика контактов Вконтакте есть 5 разных пакета, которые отличаются длительностью действия и количество
            доступных запросов на скачивание контактов в день</p>

          <p>Изначально вы получаете реферальные в <b>15% с первой линии и 0% со второй</b></p>

          <p>Чтобы получить реферальные в <b>30% с первой линии и 20% со второй</b> вам необходимо:</p>
          <ul>
            <li>оплатить пакет <b class="text-navy">Skilled120 или выше</b>;</li>
            <li><b>10 ваших лично-приглашенных человек</b>, должны оплатить пакет
              <b class="text-navy">Skilled120 или выше</b></li>
          </ul>

          <p>Чтобы получить реферальные в <b>45% с первой линии и 30% со второй</b> вам необходимо:</p>
          <ul>
            <li>оплатить пакет <b class="text-navy">Seasoned240 или выше</b>;</li>
            <li><b>5 ваших лично-приглашенных человек</b>, должны оплатить пакет
              <b class="text-navy">Seasoned240 или выше</b></li>
          </ul>
        </div>
    <%- end -%>
<%- end -%>