config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
	scope constraints: { subdomain: '' } do
		root 'tnf_landing_page#index'
	end

	scope '/auth', constraints: { subdomain: 'work' } do
		devise_for :users
	end

	scope constraints: { subdomain: 'work' }, as: :work do

		root 'static_pages#dashboard'

		resource :user, only: [] do
			post :pay_out
		end
		resource :user_profile, only: [:edit, :update]
		resources(:user_vk_contacts_files, only: [:index, :show, :update, :edit]) { member { get :download } }
		resources(:user_vk_contacts_records, only: [:index, :update, :edit, :destroy]) { member { get :download } }

		get 'vkontakte_contacts_collector', to: 'static_pages#vkontakte_contacts_collector'
		get 'pricing_plans', to: 'static_pages#pricing_plans'
		get 'pmvf', to: 'static_pages#pmvf'
		get 'referrals', to: 'static_pages#referrals'
		get 'faq', to: 'static_pages#faq'

		scope 'vkontakte_oauth', as: :vk_o_auth do
			get 'authorize', to: 'vk_o_auth#authorize'
			get 'logout', to: 'vk_o_auth#logout'
		end

		scope 'vkontakte_contacts', as: :vkontakte_contacts do
			post 'upload', to: 'vk_contacts_load#upload_contacts'
		end

		namespace :admin do
			root 'static_pages#dashboard'
			resources :users, only: [:index, :edit, :show, :update]
			resources :perfect_money_merchant_accounts
			resources :perfect_money_merchant_payments
		end

		authenticate :user do
			mount Sidekiq::Web => '/admin/sidekiq'
		end
	end
end

app/controllers/admin/perfect_money_merchant_accounts_controller.rb
class Admin::PerfectMoneyMerchantAccountsController < Admin::ApplicationController
	def index
		@accounts = PerfectMoneyMerchant::Account.all
	end

	def create
		@account = PerfectMoneyMerchant::Account.new(create_params)

		respond_to do |format|
			if @account.save
				format.html { redirect_to work_admin_perfect_money_merchant_accounts_path, notice: 'Product was successfully created.' }
				# format.json { render json: @account, status: :created, location: @product }
			else
				format.html { render action: "new" }
				# format.json { render json: @account.errors, status: :unprocessable_entity }
			end
		end
	end

	def new
		@account = PerfectMoneyMerchant::Account.new.tap do |_obj|
			_obj.units.build
		end
	end

	def edit
		@account = PerfectMoneyMerchant::Account.find(params[:id]).tap do |_obj|
			_obj.units.build
		end
	end

	def update
		@account = PerfectMoneyMerchant::Account.find(params[:id])

		respond_to do |format|
			if @account.update_attributes(update_params)
				format.html { redirect_to work_admin_perfect_money_merchant_accounts_path, notice: 'Product was successfully updated.' }
				# format.json { head :no_content }
			else
				format.html { render action: "edit" }
				# format.json { render json: @account.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy

	end

	private

	def create_params
		params.require(:perfect_money_merchant_account).permit(:login, :password, :secret_key, units_attributes: [:id, :currency, :code_number])
	end

	def update_params
		params.require(:perfect_money_merchant_account).permit(:login, :password, :secret_key, units_attributes: [:id, :currency, :code_number, :_destroy])
	end
end

app/views/admin/perfect_money_merchant_accounts/_form.html.erb
<%= simple_form_for resource, url: resource_url, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| -%>
    <%= field_set_tag 'Perfect Money Account' do -%>
        <%= f.input :login -%>
        <%= f.input :password, as: :string -%>
        <%= f.input :secret_key -%>
    <%- end -%>
    <%= f.simple_fields_for :units do |_unit| -%>
        <%= field_set_tag 'Wallet/Currency Account/Unit' do -%>
            <%= _unit.input :currency, required: false -%>
            <%= _unit.input :code_number, required: false -%>
            <%= _unit.input :_destroy, as: :radio_buttons,label: 'Want to remove?' -%>
        <%- end -%>
    <%- end -%>
    <div class="row">
      <div class="col-sm-offset-3 col-sm-9">
        <%= f.button :submit, class: 'btn-primary' %>
      </div>
    </div>
<%- end -%>

app/views/admin/perfect_money_merchant_accounts/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= ah_ibox do -%>
        <%= ah_ibox_title('Edit Perfect Money Merchant Account') -%>
        <%= ah_ibox_content do -%>
            <%= render 'form', resource: @account, resource_url: work_admin_perfect_money_merchant_account_path(@account) -%>
        <%- end -%>
    <%- end -%>
  </div>
</div>

app/views/admin/perfect_money_merchant_accounts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= ah_ibox do -%>
        <%= ah_ibox_title('Perfect Money Merchant Accounts') -%>
        <%= ah_ibox_content do -%>
            <%= link_to t('translations.create'), new_work_admin_perfect_money_merchant_account_path, class: 'btn btn-white' -%>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>ID</th>
                <th>Login</th>
                <th>Password</th>
                <th>Secret key</th>
                <th>Units quantity</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <%- @accounts.each do |_account| -%>
                  <tr>
                    <td><%= _account.id -%></td>
                    <td><%= _account.login -%></td>
                    <td><%= _account.password -%></td>
                    <td><%= _account.secret_key -%></td>
                    <td><%= _account.units.count -%></td>
                    <td class="text-right">
                      <%= link_to work_admin_perfect_money_merchant_account_path(_account), class: 'btn btn-white btn-sm' do -%>
                          <%= fa_icon('eye') -%>
                      <%- end -%>
                      <%= link_to edit_work_admin_perfect_money_merchant_account_path(_account), class: 'btn btn-white btn-sm' do -%>
                          <%= fa_icon('pencil') -%>
                      <%- end -%>
                    </td>
                  </tr>
              <%- end -%>
              </tbody>
            </table>
        <%- end -%>
    <%- end -%>
  </div>
</div>

app/views/admin/perfect_money_merchant_accounts/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= ah_ibox do -%>
        <%= ah_ibox_title('New Perfect Money Merchant Account') -%>
        <%= ah_ibox_content do -%>
            <%= render 'form', resource: @account, resource_url: work_admin_perfect_money_merchant_accounts_path -%>
        <%- end -%>
    <%- end -%>
  </div>
</div>