config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
	scope constraints: { subdomain: '' } do
		root 'tnf_landing_page#index'
	end

	scope '/auth', constraints: { subdomain: 'work' } do
		devise_for :users
	end

	scope constraints: { subdomain: 'work' }, as: :work do

		root 'static_pages#dashboard'

		resource :user, only: [] do
			post :pay_out
		end
		resource :user_profile, only: [:edit, :update]
		resources(:user_vk_contacts_files, only: [:index, :show, :update, :edit]) { member { get :download } }
		resources(:user_vk_contacts_records, only: [:index, :update, :edit, :destroy]) { member { get :download } }

		get 'vkontakte_contacts_collector', to: 'static_pages#vkontakte_contacts_collector'
		get 'pricing_plans', to: 'static_pages#pricing_plans'
		get 'pmvf', to: 'static_pages#pmvf'
		get 'referrals', to: 'static_pages#referrals'
		get 'faq', to: 'static_pages#faq'

		scope 'vkontakte_oauth', as: :vk_o_auth do
			get 'authorize', to: 'vk_o_auth#authorize'
			get 'logout', to: 'vk_o_auth#logout'
		end

		scope 'vkontakte_contacts', as: :vkontakte_contacts do
			post 'upload', to: 'vk_contacts_load#upload_contacts'
		end

		namespace :admin do
			root 'static_pages#dashboard'
			resources :users, only: [:index, :edit, :show, :update]
			resources :perfect_money_merchant_accounts
			resources :perfect_money_merchant_payments
		end

		authenticate :user do
			mount Sidekiq::Web => '/admin/sidekiq'
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

	has_one :user_profile, dependent: :destroy, inverse_of: :user
	has_one :user_vk_contacts_collector_permission, dependent: :destroy, inverse_of: :user

	belongs_to :inviter, class_name: 'User', foreign_key: :inviter_id

	has_many :user_vk_contacts_records, inverse_of: :user, dependent: :destroy

	has_many :referrals, class_name: 'User', foreign_key: :inviter_id

	has_many :user_referral_payments, dependent: :destroy

	accepts_nested_attributes_for :user_vk_contacts_collector_permission
	accepts_nested_attributes_for :user_profile

	validates :referral_earned, :referral_paid_out, numericality: { greater_than_or_equal_to: 0 }
	validates :referral_award_level_1, :referral_award_level_2, numericality: {
			greater_than_or_equal_to: 0,
			less_than_or_equal_to: 50
		}

	alias_method :vcc_permission, :user_vk_contacts_collector_permission
	alias_method :profile, :user_profile


	module Extensions
		module DeviseSignUp
			INVITE_MODEL = 'UserProfile'
			INVITE_CODE_FIELD = :username

			extend ActiveSupport::Concern

			class DepsInitializer
				attr_reader :user, :opts

				def initialize(user, opts = {})
					@user = user
					@opts = opts
				end

				def run
					_build_user_profile
					_build_user_vk_contacts_collector_permission
					_set_as_admin
					_set_inviter_id
					_set_referral_award
				end

				private

				def _build_user_profile
					user.build_user_profile
				end

				def _build_user_vk_contacts_collector_permission
					user.build_user_vk_contacts_collector_permission
				end

				def _set_as_admin
					user.is_admin = true if User.count.zero?
				end

				def _set_inviter_id
					unless User.count.zero?
						user.inviter_id = UserProfile.where(INVITE_CODE_FIELD => user.invite_code).take(1).first.user_id
					end
				end

				def _set_referral_award
					user.referral_award_level_1 = 45
					user.referral_award_level_2 = 30
				end
			end

			included do
				attr_accessor :invite_code
				validate :ensure_invite_code_exists, if: Proc.new { new_record? }
				before_create :initialize_deps
			end

			def initialize_deps
				DepsInitializer.new(self).run
			end

			def ensure_invite_code_exists
				unless User.count.zero?
					if invite_code.nil?
						add_invite_code_error(:blank)
					else
						add_invite_code_error unless UserProfile.exists?(INVITE_CODE_FIELD => invite_code)
					end
				end
			end

			private

			def add_invite_code_error(message = :invalid)
				singleton_class.send(:attr_reader, :invite_code)
				errors.add(:invite_code, message)
			end
		end

		module Functions
			def referral_award_level(level)
				respond_to?("referral_award_level_#{level}") ? send("referral_award_level_#{level}") : 0
			end

			def has_permission?(name, type)
				case type
				when :vk_contacts_collector
					if name.is_a?(Array)
						name.include?(vcc_permission.package.to_sym)
					else
						vcc_permission.package.to_sym == name
					end
				else
					false
				end
			end

			def get_referrals_by(opts = {})
				raise_invalid_args = Proc.new { raise '#referrals_with: invalid args' }
				if opts[:vk_contacts_collector]
					if opts[:vk_contacts_collector][:package_name]
						case opts[:vk_contacts_collector][:package_name]
						when :skilled_120_or_greater
							referrals.joins(:user_vk_contacts_collector_permission).where(user_vk_contacts_collector_permissions: { package: ['skilled_120', 'seasoned_240', 'advanced_360'] })
						when :seasoned_240_or_greater
							referrals.joins(:user_vk_contacts_collector_permission).where(user_vk_contacts_collector_permissions: { package: ['seasoned_240', 'advanced_360'] })
						when :newbie_30, :novice_60, :skilled_120, :seasoned_240, :advanced_360
							referrals.joins(:user_vk_contacts_collector_permission).where(user_vk_contacts_collector_permissions: { package: opts[:vk_contacts_collector][:package_name] })
						else
							raise_invalid_args.call()
						end
					else
						raise_invalid_args.call()
					end
				else
					raise_invalid_args.call()
				end
			end
		end
	end

	include Extensions::DeviseSignUp
	include Extensions::Functions
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	def index
		@users = User.all.order('created_at DESC')
	end

	def edit
		@user = User.find(params[:id])
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		respond_to do |format|
			if @user.update(update_params)
				format.html { redirect_to work_admin_user_path(@user), notice: 'User was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def update_params
		params.require(:user).permit(
			:email,
			:is_admin,
			:referral_earned,
			:referral_award_level_1,
			:referral_award_level_2,
			:inviter_id,
			user_vk_contacts_collector_permission_attributes: [
				:id,
				:package,
				:expires_at,
				:requests_limit_per_day,
				:can_create,
				:can_read,
				:can_update,
				:can_delete
			],
			user_profile_attributes: [
				:id,
				:first_name,
				:last_name,
				:about,
				:country,
				:city,
				:skype,
				:contact_phone,
				:contact_email,
				:vkontakte_id,
				:facebook_id,
				:twitter_id,
				:pm_usd_acct,
				:username
			]
		)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def pay_out
		respond_to do |format|
			if current_user.decorate.referral_balance > 0
				if UserReferralManager.new(current_user).pay_out(current_user.decorate.referral_balance)
					format.html { redirect_to :back }
					format.json { head :no_content }
				else
					format.html { redirect_to :back, alert: 'Вывести деньги не получилось. Возникла ошибка. Мы уже ее решаем' }
					format.json { head :no_content }
				end
			end
		end
	end
end

app/views/admin/users/_table.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Поле</th>
      <th>Значение</th>
    </tr>
    </thead>
    <tbody>
    <%- ar_object.attributes.each do |_attr_name, _attr_value| -%>
        <tr>
          <td><%= ar_object.class.human_attribute_name(_attr_name.to_sym) %></td>
          <td><%= _attr_value %></td>
        </tr>
    <%- end -%>
    </tbody>
  </table>
</div>

app/views/admin/users/edit.html.erb
<div class="row">
  <%= simple_form_for @user, url: work_admin_user_path(@user), html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| -%>
      <%= ah_ibox do %>
          <%= ah_ibox_title('User') %>
          <%= ah_ibox_content do %>

              <%= f.error_notification %>
              <%= f.input :email, required: true %>
              <%= f.input :is_admin %>
              <%= f.input :inviter_id %>
              <%= f.input :referral_earned %>
              <%= f.input :referral_paid_out, disabled: true %>
              <%= f.input :referral_award_level_1 %>
              <%= f.input :referral_award_level_2 %>

              <div class="row">
                <div class="col-sm-offset-3 col-sm-9">
                  <%= f.button :submit, class: 'btn-primary' %>
                </div>
              </div>
          <%- end -%>
      <% end %>
      <%= ah_ibox do %>
          <%= ah_ibox_title('Vk Contacts Collector Permissions') %>
          <%= ah_ibox_content do %>
              <%= f.simple_fields_for :user_vk_contacts_collector_permission, @user.user_vk_contacts_collector_permission do |user_vk_contacts_collector_permission| -%>
                  <%= user_vk_contacts_collector_permission.input :package, collection: %w(newbie_30 novice_60 skilled_120 seasoned_240 advanced_360) %>
                  <%= user_vk_contacts_collector_permission.input :expires_at, as: :date_time_picker %>
                  <%= user_vk_contacts_collector_permission.input :requests_limit_per_day %>
                  <%= user_vk_contacts_collector_permission.input :can_create %>
                  <%= user_vk_contacts_collector_permission.input :can_read %>
                  <%= user_vk_contacts_collector_permission.input :can_update %>
                  <%= user_vk_contacts_collector_permission.input :can_delete %>
                  <div class="row">
                    <div class="col-sm-offset-3 col-sm-9">
                      <%= user_vk_contacts_collector_permission.button :submit, class: 'btn-primary' %>
                    </div>
                  </div>
              <%- end -%>
          <%- end -%>
      <% end %>

      <%= ah_ibox do %>
          <%= ah_ibox_title('Profile') %>
          <%= ah_ibox_content do %>
              <%= f.simple_fields_for :user_profile, @user.user_profile do |user_profile| -%>
                  <%= user_profile.input :first_name %>
                  <%= user_profile.input :last_name %>
                  <%= user_profile.input :about %>
                  <%= user_profile.input :country %>
                  <%= user_profile.input :city %>
                  <%= user_profile.input :skype %>
                  <%= user_profile.input :contact_phone %>
                  <%= user_profile.input :contact_email %>
                  <%= user_profile.input :vkontakte_id %>
                  <%= user_profile.input :facebook_id %>
                  <%= user_profile.input :twitter_id %>
                  <%= user_profile.input :pm_usd_acct %>
                  <%= user_profile.input :username %>
                  <div class="row">
                    <div class="col-sm-offset-3 col-sm-9">
                      <%= user_profile.button :submit, class: 'btn-primary' %>
                    </div>
                  </div>
              <%- end -%>
          <%- end -%>
      <% end %>
  <% end %>
</div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= ah_ibox do -%>
        <%= ah_ibox_title('Users') -%>
        <%= ah_ibox_content do -%>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>ID</th>
                <th>Inviter ID</th>
                <th>Email</th>
                <th>First name</th>
                <th>Last name</th>
                <th><%= fa_icon('vk') %></th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <%- @users.each do |_user| -%>
                  <tr>
                    <td><%= _user.id -%></td>
                    <td><%= _user.inviter_id -%></td>
                    <td><%= _user.email -%></td>
                    <td><%= _user.user_profile.first_name -%></td>
                    <td><%= _user.user_profile.last_name -%></td>
                    <td><%= _user.decorate.current_vcc_package -%></td>
                    <td class="text-right">
                      <%= link_to work_admin_user_path(_user), class: 'text-muted' do -%>
                          <%= fa_icon('folder-open', text: 'Open') -%>
                      <%- end -%>
                    </td>
                  </tr>
              <%- end -%>
              </tbody>
            </table>
        <%- end -%>
    <%- end -%>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="m-b">
      <%= link_to 'Все пользователи', work_admin_users_url, class: 'btn btn-primary' %>
      <%= link_to 'Редактировать', edit_work_admin_user_path(@user), class: 'btn btn-warning' %>
    </div>

    <%= ah_ibox do %>
        <%= ah_ibox_title('Страница пользователя') %>
        <%= ah_ibox_content do %>
            <div class="panel-group" id="pmvf-faq-accordion">
              <div class="panel">
                <div class="panel-heading active-panel">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse1">
                      Данные о пользователе и рефералы
                    </a>
                  </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse">
                  <div class="panel-body">
                    <%= render partial: 'table', locals: { ar_object: @user } %>
                    <%= render partial: 'static_pages/referrals/table', locals: { referrals: @user.referrals } %>
                  </div>
                </div>
              </div>
              <div class="panel">
                <div class="panel-heading active-panel">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse2">
                      Данные о профиля пользователя
                    </a>
                  </h4>
                </div>
                <div id="collapse2" class="panel-collapse collapse">
                  <div class="panel-body">
                    <%= render partial: 'table', locals: { ar_object: @user.user_profile } %>
                  </div>
                </div>
              </div>
              <div class="panel">
                <div class="panel-heading active-panel">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse4">
                      Данные о доступе пользователя к сборщику контактов ВК
                    </a>
                  </h4>
                </div>
                <div id="collapse4" class="panel-collapse collapse">
                  <div class="panel-body">
                    <%= render partial: 'table', locals: { ar_object: @user.user_vk_contacts_collector_permission } %>
                  </div>
                </div>
              </div>
              <div class="panel">
                <div class="panel-heading active-panel">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#pmvf-faq-accordion" href="#collapse3">
                      Скачанные источники ВК
                    </a>
                  </h4>
                </div>
                <div id="collapse3" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="table-responsive">
                      <ul>

                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        <%- end -%>
    <%- end -%>
  </div>
</div>